function generate(){
	var firstname = ["No importa cuán difícil sea la vida, siempre hay una razón para seguir adelante.","Cada día es una nueva oportunidad para comenzar de nuevo y hacer algo grande.","A veces, las mejores cosas de la vida están al final del camino más difícil.","Siempre hay una luz al final del túnel, incluso si no puedes verla ahora mismo.","Tu vida es valiosa y significativa, no importa lo que te diga la gente.","No te rindas en tus sueños, puedes alcanzar todo lo que te propongas.","No puedes controlar todas las situaciones de la vida, pero puedes controlar cómo reaccionas ante ellas.","Incluso cuando sientes que no tienes nada, siempre hay algo que puedes hacer para marcar la diferencia.","La felicidad es una elección que puedes hacer cada día, independientemente de las circunstancias.","El fracaso es parte del proceso hacia el éxito; no te desanimes por un revés.","La vida puede ser difícil, pero también puede ser hermosa y gratificante.","Tu vida tiene un propósito, incluso si todavía no lo has descubierto.","La resiliencia es una habilidad que puedes desarrollar con el tiempo; nunca es demasiado tarde para aprender.","La felicidad no se trata de tener todo lo que quieres, sino de apreciar lo que tienes.","A veces, las mejores cosas de la vida son aquellas que no podemos ver ni tocar.","Cada persona tiene algo valioso que ofrecer al mundo; descubre lo que te hace único y úsalo para hacer una diferencia positiva.","No permitas que las opiniones de otras personas te impidan vivir tu vida al máximo.","Aprender a perdonar es una forma de liberarte de la carga del pasado y avanzar hacia un futuro mejor.","Siempre hay esperanza, incluso en los momentos más oscuros.","Cada día es una oportunidad para hacer algo bueno por ti mismo y por los demás. Aprovecha esa oportunidad y haz que cuente.","A veces, el mayor crecimiento y aprendizaje ocurren a través de las luchas y los desafíos que enfrentamos.","La vida es un regalo y es importante recordar agradecer por ello todos los días.","No dejes que el miedo te detenga de hacer lo que realmente quieres en la vida.","A veces, lo que parece un final puede ser el comienzo de algo nuevo y emocionante.","No te compares con los demás; cada persona tiene su propio camino en la vida y sus propias luchas.","El éxito no es solo sobre el dinero y la fama; también se trata de encontrar la felicidad y la satisfacción personal."];

	var rand_first = Math.floor(Math.random()*firstname.length); 	
	document.getElementById('result').innerHTML = "<h1>lee me:</h1><div class='alert alert-success'><h2>"+firstname[rand_first]+"</h2></div>";
}



